### ISSUE TITLE
Use with Next.js?

### ISSUE THREAD

**Issue by curran** [dmapper/react-sharedb#2]
Greetings,

I'm excited to see a new, clean implementation of React + ShareDB integration.

One feature I'm looking for is server rendering.

Any ideas on how this library could be integrated into a [Next.js][(https://github.com/zeit/next.js/) app?

Also, do you have any example apps available that use this library?

Thank you.

**Comment by cray0000** [comment]
Well, it's definitely possible to render it using the React server rendering. Though you would need to work on properly setting it up and provide polyfill for the client `model` on the server. 

Usage example is now in readme. Server side setup is described in the `sharedb` library and in the `racer-highway` library (used for websockets communication). You can also take a look at `test` folder which actually also does the server side rendering of client code.

Unfortunately I don't have time atm to create a full working example with server side, but if you happen to do it, I'd be glad to accept a PR

**Comment by curran** [comment]
Very nice! Thank you @cray0000 for your response.

**Comment by OSP123** [comment]
Yeah, would love to see something like this. I've been messing around with refactoring the existing library to use with React and come up on this library. Currently using React/Next/Express and would love to have integration examples for that stack, if possible! @curran If you have it working, would it be cool if you shared your approach?

**Comment by curran** [comment]
@OSP123 Here's a codebase I worked on that has a working integration with Next.js https://github.com/datavis-tech/datavis-tech-app-legacy

Here's another, but it doesn't yet use ShareDB in the client side https://github.com/datavis-tech/vizhub

**Comment by OSP123** [comment]
Sick, thanks man :)
