### ISSUE TITLE
Example App

### ISSUE THREAD

**Issue by curran** [dmapper/react-sharedb#8]
It's not clear from the README, is there a working demo example app that shows how to use this library? Thanks!

**Comment by cray0000** [comment]
nope, no example app atm. I'll be releasing the better docs system and example apps as part of the bigger framework which going to release in several months from now. Please refer to another issue where I describe how to run it

**Comment by curran** [comment]
Thanks for letting me know! I'll let you know if I experiment and get something working.

**Comment by curran** [comment]
@cray0000 I see some activity picking up here. Any example programs to try out yet? Thanks!

**Comment by cray0000** [comment]
@curran I've released a full framework ([StartupJS](https://github.com/startupjs/startupjs)) as an extension of my work on `react-sharedb`, so here is your long awaited example program:

```npx startupjs init myapp```

😄 

It also has lots of additional patches to `Racer` (like the full `Promise` api support and various bug fixes).

**Comment by curran** [comment]
Very cool! Will have a look there.

I suppose we can close the issue then.
