### ISSUE TITLE
Release hooks

### ISSUE THREAD

**Issue by JanMatas** [dmapper/react-sharedb#9]
Hi,

thanks for this great looking library! I am considering replacing custom build collaboration in my project with sharedb. Your library looks great and I was excited to see you allow hooks syntax.

Are you going to release this on npm soon?

**Comment by curran** [comment]
I'm interested in this as well. Considering rolling my own implementation as I'm not sure how to get started with this library (see #8 ).

**Comment by cray0000** [comment]
Hi! It's already on npm. The latest version with hooks is under the `alpha` tag. `npm i react-sharedb@alpha`

Will promote it to `latest` whithin the next 2-3 weeks. We already use hooks in production though for about 2 months, and I can say that it's already more stable compared to the previous classes-version.
